import { StyleSheet } from 'react-native';

export const pagesStyles = StyleSheet.create({
  container: {
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'center',
    alignItems: 'center',
  },
  contentContainer: {
    width: '70%',
  },
  decoration: {
    fontFamily: 'Assistant-VariableFont_wght',
    color: '#545454',
    fontSize: 14,
    lineHeight: 18,
    textAlign: 'center',
    fontWeight: '600',
  },
  h1: {
    fontFamily: 'Assistant-VariableFont_wght',
    textAlign: 'center',
    color: '#000000',
    fontStyle: 'normal',
    fontWeight: '800',
    fontSize: 20,
    lineHeight: 26,
  },
  h2: {
    fontFamily: 'Assistant-VariableFont_wght',
    textAlign: 'center',
    color: '#000000',
    fontStyle: 'normal',
    fontWeight: '600',
    fontSize: 15,
    lineHeight: 20,
},
  input: {
    borderBottomWidth: 0.8,
    borderColor: '#707070',
    fontFamily: 'Assistant-VariableFont_wght',
    fontWeight: '200',
    fontSize: 13,
    lineHeight: 16,
    fontStyle: 'normal',
    color: '#707070',
    marginVertical: '1%',
    paddingLeft: 10,
    paddingBottom: 5
  },
  button: {
    borderRadius: 20,
    marginTop: '5%',
    borderWidth: 0.8,
    borderColor: 'rgba(86, 86, 86, 1)',
    paddingTop: 10,
    paddingBottom: 10,
    justifyContent: 'center',
    alignItems: 'center',
  },
  navigation: {
    fontStyle: 'normal',
    fontWeight: '400',
    fontSize: 15,
    lineHeight: 20,
    color: '#707070',
    textAlign: 'center',
  },
  buttonText: {
    color: '#2A7DEE',
    textAlign: 'center',
    lineHeight: 24,
    fontSize: 18,
    fontWeight: '800',
    fontStyle: 'normal',
    fontFamily: 'Assistant-VariableFont_wght',
  },
  choose: {
    fontFamily: 'Assistant-VariableFont_wght',
    fontSize: 15,
    fontWeight: '400',
    fontStyle: 'normal',
    lineHeight: 20,
    textAlign: 'center',
    color: '#2B2B2B',
    textDecorationLine: 'underline',
  },
  questions: {
    fontFamily: 'Assistant-VariableFont_wght',
    fontWeight: '200',
    fontSize: 12,
    lineHeight: 16,
    fontStyle: 'normal',
    color: '#000000',
    textAlign: 'center',
  }
});